DUBINS: true
USING_TORCH: true

# STATE_ESTIMATOR: "tiny_taxinet"
STATE_ESTIMATOR: "dnn"
ATTACK: static_atk_dnn # null means None in YAML
# ATTACK options could be: null, static_atk, static_atk_dnn
# ATTACK_STRENGTH: 0.049
ATTACK_STRENGTH: 0.025
FILTER: false

TIME_OF_DAY: 8.0
CLOUD_COVER: 0

START_CTE: 6.0
START_HE: 0.0 
START_DTP: 322.0
END_DTP: 522.0

DT: 0.1
CTRL_EVERY: 1