DUBINS: true
USING_TORCH: false

STATE_ESTIMATOR: "tiny_taxinet"
ATTACK: pgd
# ATTACK_STRENGTH: 0.021


# STATE_ESTIMATOR: "cnn"
# ATTACK: fgsm   # null means None in YAML
# ATTACK: static_atk
# ATTACK options could be: null, static_atk, static_atk_dnn, fgsm, pgd
# ATTACK_STRENGTH: 0.049
# ATTACK_STRENGTH: 0.0005
SMOOTHING: true
SMOOTHING_ALPHA: 0.5

ATTACK_STRENGTH: 0.023
# ATTACK_STRENGTH: 0.021
# ATTACK_STRENGTH: 0.00001
TARGET: 7.0
# ATTACK_STRENGTH: 0.005
FILTER: true
CTE_BUFFER: 3.5
HE_BUFFER: 25.0

TIME_OF_DAY: 8.0
CLOUD_COVER: 0

START_CTE: -9.5
START_HE: 0.0 
START_DTP: 322.0
END_DTP: 522.0

DT: 0.1
CTRL_EVERY: 1