DUBINS: true
USING_TORCH: false

STATE_ESTIMATOR: "cnn64" # "tiny_taxinet", "cnn64", "cnn"
ATTACK: null # null, pgd, fgsm
SMOOTHING: false
SMOOTHING_ALPHA: 0.5

ATTACK_STRENGTH: 0.022
TARGET: 7.0

FILTER: false
CTE_BUFFER: 3.0
HE_BUFFER: 30.0

TIME_OF_DAY: 8.0
CLOUD_COVER: 0

START_CTE: -8.0
START_HE: 0.0 
START_DTP: 322.0
END_DTP: 522.0

DT: 0.1
CTRL_EVERY: 1