DUBINS: true
USING_TORCH: false

STATE_ESTIMATOR: "tiny_taxinet" # "tiny_taxinet", "cnn64", "cnn"
ATTACK: pgd # null, pgd, fgsm
SMOOTHING: true
SMOOTHING_ALPHA: 0.5
PGD_ALPHA: 0.005
PGD_STEPS: 40

ATTACK_STRENGTH: 0.021

FILTER: true
CTE_BUFFER: 1.5 # tiny_taxinet: 3.0
HE_BUFFER: 10.0 # tiny_taxinet: 30.0

TIME_OF_DAY: 8.0
CLOUD_COVER: 0

START_CTE: -5.0
START_HE: 0.0 
START_DTP: 200.0
END_DTP: 300.0

DT: 0.1
MAX_RUDDER: 12.0
CTRL_EVERY: 1